<?php



?>


<div id="product_info_tabs_categories_content" style=""><div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend">Product Categories</h4>
        </div>
        <fieldset id="grop_fields">
            <input name="category_ids" id="product_categories" value="" type="hidden">
            <table class="form-list" cellspacing="0">
                <tbody>



                <tr>
                    <td class="label"><label for="store_root_category">Select Store Root Category</label></td>
                    <td class="value">
                        <select id="store_root_category" name="store_root_category" class=" select">
                            <option value="123">123</option>

                        </select>
                    </td>
                    <td class="scope-label"><span class="nobr">[GLOBAL]</span></td>
                </tr>
                </tbody>
                </table>
        </fieldset>
    </div>

</div>