<?php




$req = $this->getRequest()->getParams();

$storeconfId = $req['id'];

$dat = Mage::getSingleton('storeconf/storeconf')->load($storeconfId);

$back = Mage::helper('adminhtml')->getUrl('storesetup/adminhtml_store/reports');


$resource = Mage::getSingleton('core/resource');


$readConnection = $resource->getConnection('core_read');

$sellerId=$dat->getSellerId();

$storeid = $dat->getStoreName();


$resource = Mage::getSingleton('core/resource');
$readConnection = $resource->getConnection('core_read');
$visits = "SELECT log_id from log_customer where store_id=$storeid";
$strVisits= $readConnection->fetchAll($visits);
$totalStoreeVisits = count($strVisits);

$custm = "SELECT DISTINCT customer_id from log_customer";
$totalCustm= $readConnection->fetchAll($custm);
$totalcustomers = count($totalCustm);

$strcustm = "SELECT DISTINCT customer_id from log_customer where store_id=$storeid";
$totalCustmstr= $readConnection->fetchAll($strcustm);
$totalcustomersstr = count($totalCustmstr);

// Mage::getModel('seller/seller')->updateOrder($sellerId);

 /* Edited by retailon_15052 start */
   
  
  
  
    $get_seller_category=$dat->getStoreCategory();
   
    $resource = Mage::getSingleton('core/resource');
      $readConnection = $resource->getConnection('core_read');

     $allproductids = "SELECT product_id FROM catalog_category_product where category_id=$get_seller_category ";
     $allproductresult = $readConnection->fetchAll($allproductids);
     $prdIds =array();
     foreach($allproductresult as $value4)
      {
    $prdIds[]=$value4['product_id'];
      }
 
    $no_of_ele=count($prdIds);
    $sum=0;
     $all_order_id_array=array();
     $kk=0;
     $allincrementids = "SELECT increment_id FROM sales_flat_order_grid where status='complete' ";
     $allincrresult = $readConnection->fetchAll($allincrementids);
     $incr_id_array =array();
     foreach($allincrresult as $value)
      {
    $incr_id_array[]=$value['increment_id'];
      }

     foreach($incr_id_array as $value1)
     {
         $j=0;
     	$orderIncrementId =$value1;
        $order = Mage::getModel('sales/order')->loadByIncrementId($orderIncrementId);
        $required_order_id=$order->getId();       
        $items = $order->getAllVisibleItems();
          foreach($items as $value2)
            {
   	        $ids[$j++]=$value2->getProductId();   	
            } 
           

         
          foreach($ids as $value3)
           {
           	 for($i=0;$i<$no_of_ele;$i++)
           	   {
           	      if($value3==$prdIds[$i])
           	      {
           	      	
           	      	$amount="SELECT base_row_total_incl_tax,order_id FROM sales_flat_order_item where order_id=$required_order_id and product_id=$value3 ";
           	      	$temp1=$readConnection->fetchAll($amount);
           	      	 foreach($temp1 as $value12)
           	      	  {
           	      	    $sum+=$value12['base_row_total_incl_tax'];
           	      	    $all_order_id_array[$kk++]=$value12['order_id'];
           	      	 }
           	      }
           	   }
           }  
           
     }
  
 $avgorders_array=array_unique($all_order_id_array);


$lifetimesales = $sum;

$avgorders=$lifetimesales/count($avgorders_array);

 
  
$no_of_complete=0;
$no_of_pending=0;
$no_of_processing=0;
$no_of_canceled=0;

     
     $allincrementids = "SELECT increment_id,status FROM sales_flat_order_grid ";
     $allincrresult = $readConnection->fetchAll($allincrementids);
     $incr_id_array =array();
     $status_array = array();
     foreach($allincrresult as $value)
      {
    $incr_id_array[]=$value['increment_id'];
    $status_array[]=$value['status'];
      }

     foreach($incr_id_array as $key => $value1)
     {
         $j=0;
     	$orderIncrementId =$value1;
        $order = Mage::getModel('sales/order')->loadByIncrementId($orderIncrementId);
             
        $items = $order->getAllVisibleItems();
          foreach($items as $value2)
            {
   	        $ids[$j++]=$value2->getProductId();   	
            } 
           
            $flag_first=0;
         
          foreach($ids as $value3)
           {
           	 for($i=0;$i<$no_of_ele;$i++)
           	   {
           	      if($value3==$prdIds[$i])
           	      {
           	      	
           	      	if($status_array[$key]=="complete")
                    {
                      $no_of_complete++;
                      $flag_first=1;
                      break;
                    }

                    if($status_array[$key]=="pending")
                    {
                      $no_of_pending++;
                      $flag_first=1;
                      break;
                    }

                    if($status_array[$key]=="processing")
                    {
                      $no_of_processing++;
                      $flag_first=1;
                      break;
                    }
                    if($status_array[$key]=="canceled")
                    {
                      $no_of_canceled++;
                      $flag_first=1;
                      break;
                    }
           	      }
           	   }

               if($flag_first==1)
               {
                break;
               }
           }  
           
     }

$canceled = $no_of_canceled;
$pending = $no_of_pending;
$processing = $no_of_processing;

 /* Edited by retailon_15052 end */

?>

<div id="page:main-container">
    <div id="messages"></div>
    <div class="content-header">
        <h3 class="icon-head head-system-store">Report for Store - '<?php echo $dat->getStoreDisplayName() ?>'</h3>
        <p class="form-buttons">
            <button id="" title="Back" type="button" class="scalable back" onclick="setLocation('<?php echo $back ?>');" style=""><span><span><span>Back</span></span></span></button>
        </p>
    </div>
</div>
<div class="entry-edit" id="sales_order_view"><div id="sales_order_view_tabs_order_info_content" style="">
            <div id="order-messages">
            </div>
            <div class="box-left">
                <!--Order Information-->
                <div class="entry-edit">
                    <div class="entry-edit-head">
                        <h4 class="icon-head head-account">Sales Report</h4>
                    </div>
                    <div class="fieldset">
                        <table class="form-list" cellspacing="0">
                            <tbody><tr>
                                <td class="label"><label>Lifetime Sales</label></td>
                                <td class="value"><strong><?php echo   Mage::helper('core')->currency($lifetimesales, true, false) ?></strong></td>
                            </tr>
                            <tr>
                                <td class="label"><label>Average Sales</label></td>
                                <td class="value"><strong><span id="order_status"><?php echo   Mage::helper('core')->currency($avgorders, true, false) ?></span></strong></td>
                            </tr>

                            <tr>
                                <td class="label"><label>Total Store Visits</label></td>
                                <td class="value"><strong><span id="order_status"><?php echo $totalStoreeVisits;?></span></strong></td>
                            </tr>

                            <tr>
                                <td class="label"><label>Customers Visited</label></td>
                                <td class="value"><strong><span id="order_status"><?php echo $totalcustomersstr.' out of'.'  '.$totalcustomers;  ?></span></strong></td>
                            </tr>



                            </tbody></table>
                    </div>
                </div>
            </div>

            <div class="box-right">
                <!--Order Information-->
                <div class="entry-edit">
                    <div class="entry-edit-head">
                        <h4 class="icon-head head-account">Orders Report</h4>
                    </div>
                    <div class="fieldset">
                        <table class="form-list" cellspacing="0">
                            <tbody><tr>
                                <td class="label"><label>Completed</label></td>
                                <td class="value"><strong><?php echo count($avgorders_array); ?></strong></td>
                            </tr>
                            <tr>
                                <td class="label"><label>Processing</label></td>
                                <td class="value"><strong><span id="order_status"><?php echo $processing ?></span></strong></td>
                            </tr>
                            <tr>
                                <td class="label"><label>Pending</label></td>
                                <td class="value"><strong><span id="order_status"><?php echo $pending ?></span></strong></td>
                            </tr>
                            <tr>
                                <td class="label"><label>Canceled</label></td>
                                <td class="value"><strong><span id="order_status"><?php echo $canceled ?></span></strong></td>
                            </tr>

                            </tbody></table>
                    </div>
                </div>
            </div>

</div>
    </div>

<br>
                

        <table>


        </table>



<div class="entry-edit" style="margin-top:12% !important">
                    <div class="entry-edit-head"><h4>Last 5 Orders</h4></div>
                    <fieldset class="np"><div class="grid np">
<table style="border:0;" id="lastOrdersGrid_table" cellspacing="0">
        <colgroup><col>
        <col width="100">
        <col width="100">
                </colgroup><thead>
                            <tr class="headings">
                            	 <th class=" no-link"><span class="nobr">Customer Name</span></th>
                                    <th class=" no-link"><span class="nobr">Order Id</span></th>
                                    <th class=" no-link"><span class="nobr">Product Name</span></th>
                                    <th class=" no-link last"><span class="nobr">Price</span></th>
                                     <th class=" no-link last"><span class="nobr">Quantity</span></th>
                                </tr>
                    </thead>
        <tbody>
   <?php


$resource = Mage::getSingleton('core/resource');


$readConnection = $resource->getConnection('core_read');

$query = "SELECT * FROM retailon_storeorders where seller_id = $sellerId ORDER BY created_at DESC LIMIT 5   ";

$ordIds = $readConnection->fetchAll($query);
foreach($ordIds as $val)
{
    //print_r($val['created_at']);


$orderid=$val['order_id'];

$order_page =  Mage::helper('adminhtml')->getUrl('adminhtml/sales_order/view/',array('order_id'=>$orderid));
    ?>     
        
                <tr class="even pointer" onlick="setLocation('<?php echo $order_page?>')" title="<?php echo $order_page;?>">

                    <td class=" " width="20"><?php  echo $val['incr_id']?></td>
                     <td class=" " ><?php  echo $val['customer_firstname'].' '.$val['customer_lastname'] ?></td>
                     <td class=" "><?php echo  $val['product_name'] ?></td>
                    <td class=" " width="20"><?php echo   Mage::helper('core')->currency($val['base_row_total_incl_tax'], true, false) ?></td>
                    <td class="" width="8"><?php if($val['qty_invoiced']){echo (int)$val['qty_invoiced'];}else{echo $val['qty'];} ?></td>
                </tr>
           

           <?php

}
?>
           
            </tbody>
</table>
</div>
<script type="text/javascript">
//<![CDATA[
    lastOrdersGridJsObject = new varienGrid('lastOrdersGrid', '', 'page', 'sort', 'dir', 'filter');
    lastOrdersGridJsObject.useAjax = '';
            lastOrdersGridJsObject.rowClickCallback = openGridRow;
                //]]>
                
 
</script>
</fieldset>
                </div>
                
                
<div class="entry-edit" style="">
                    <div class="entry-edit-head"><h4>Last 5 Customers Vistited</h4></div>
                    <fieldset class="np"><div class="grid np">
<table style="border:0;" id="lastOrdersGrid_table" cellspacing="0">
        <colgroup><col>
        <col width="100">
        <col width="100">
                </colgroup><thead>
                            <tr class="headings">
                                  <th class=" no-link"><span class="nobr">Customer Id</span></th>
                            	 <th class=" no-link"><span class="nobr">Customer Name</span></th>
                                    <th class=" no-link"><span class="nobr">Customer Email</span></th>
                                   
                                </tr>
                    </thead>
        <tbody>
   <?php


$resource = Mage::getSingleton('core/resource');


$readConnection = $resource->getConnection('core_read');



$strcustmlogin = "SELECT DISTINCT customer_id from log_customer where store_id=$storeid ORDER BY login_at DESC LIMIT 5 ";
$totalCustmstrlogin= $readConnection->fetchAll($strcustmlogin);

foreach($totalCustmstrlogin as $ata)
{
    ?>     
        
                <tr class="even pointer" onlick="" title="">

                     <td class=" " width="10"><?php  echo $ata['customer_id'];?></td>
                     <td class=" " ><?php  echo Mage::getSingleton('customer/customer')->load($ata['customer_id'])->getName(); ?></td>
                     <td class=" "><?php echo Mage::getSingleton('customer/customer')->load($ata['customer_id'])->getEmail(); ?></td>


                </tr>
           

           <?php

}
?>
           
            </tbody>
</table>
</div>
<script type="text/javascript">
//<![CDATA[
    lastOrdersGridJsObject = new varienGrid('lastOrdersGrid', '', 'page', 'sort', 'dir', 'filter');
    lastOrdersGridJsObject.useAjax = '';
            lastOrdersGridJsObject.rowClickCallback = openGridRow;
                //]]>
                
 
</script>
</fieldset>
                </div>
                
